create table pitcher_by_season (
  player_id varchar,
  player_name varchar,
  team_id varchar,
  season varchar,
  t_game numeric,
  era numeric,
  win numeric,
  lose numeric,
  save numeric,
  hold numeric,
  wra numeric,
  pa numeric,
  ab numeric,
  bf numeric,
  inn numeric,
  hit numeric,
  hr numeric,
  sh numeric,
  sf numeric,
  bb numeric,
  ibb numeric,
  hp numeric,
  kk numeric,
  wp numeric,
  bk numeric,
  r numeric,
  er numeric,
  whip numeric,
  oavg numeric,
  k9k7 numeric,
  uploaded_at timestamp default current_timestamp
);
