create table batter_by_season (
  player_id varchar,
  player_name varchar,
  team_id varchar,
  season varchar,
  t_game numeric,
  avg numeric,
  pa numeric,
  ab numeric,
  run numeric,
  t_hit numeric,
  hit1 numeric,
  hit2 numeric,
  hit3 numeric,
  hr numeric,
  t_base numeric,
  rbi numeric,
  sb numeric,
  cs numeric,
  sh numeric,
  sf numeric,
  bb numeric,
  ib numeric,
  hp numeric,
  kk numeric,
  gd numeric,
  slg numeric,
  obp numeric,
  sba numeric,
  m_hit numeric,
  ops numeric,
  phhra numeric,
  kk_bb numeric,
  xbh_hit numeric,
  uploaded_at timestamp default current_timestamp
);
